bbox: [-91.7635618, 31.1946563, -91.7035031, 31.2287368]
output_dir: 'C:\data\mlc_test'
loc_tag: 'red_river'
project_name: "water-seg-wdm230"
dilation_iterations: 10

dem:
  n_subboxes: 5
  sigma: 2

sentinel:
  num_samples: 5

classification:
  num_samples: 5000

meshing:
  size: 50
  smoothing_iterations: 10

hotstart:
  enabled: true              # turn on hotstart generation
  mode: constant_depth            # treat ‘value’ as the depth to apply everywhere
  value: 5                   # constant water depth = 5 m (i.e. water surface elevation)
  use_initial_velocity: false

boundary:
  global_material:
    G: [9.80665]
    RHO: [1000]
    MU: [1e-6]
    MUC: [1.0]
  material:
    - type: EVS
      region: 1
      params: [0.005, 0.005, 0.0]
    - type: ML
      region: 1
      params: [4]
    - type: SRT
      region: 1
      params: [1e-4]
    - type: EVS
      region: 2
      params: [0.005, 0.005, 0.0]
    - type: ML
      region: 2
      params: [4]
    - type: SRT
      region: 2
      params: [1e-4]
  iteration:
    NIT: [6]
    MIT: [100]
    NTL: [1e-5]
  operation:
    SW2: null
    INC: [40]
    BLK: [10]
    TRN: [0]
    PRE: [1]
  boundary_strings:
    MTS:
      - [1, 1]
      - [2, 2]
  time_series:
    - type: XY1
      id: 1
      data:
        - [0.0, 0.0]
        - [3600, 1.5]
  nb:
    OTW: [1]
  friction:
    MNG:
      - region: 1
        params: [0.03]
  time_controls:
    T0: [0]
    TF: [1000]
    IDT: [1]
  output_control:
    OC: [1]

