bbox: [-91.7635618, 31.1946563, -91.7035031, 31.2287368]
output_dir: '/output/dir/here'
loc_tag: 'location_tag_here'
project_name: "project-name-here"


shapefile: false
shapefile_path: "shapefile/path/here"

exclusion:
  enabled: false
dem:
  n_subboxes: 10
  sigma: 2

sentinel:
  num_samples: 10
  scale: 20
  start_date: '2023-01-01'
  end_date: '2023-06-30'

classification:
  num_samples: 5000
  dilation_iterations: 2
  erosion_iterations: 2

meshing:
  curvi: true
  ni: 25
  nj: 125
  size: 20.0
  smoothing_iterations: 10
  chaikin_alpha:       0.5
  resample_len_frac:   0.10
  boundary_tol: 7.0
  interactive: true

bathymetry:
  shape: parabola
  bottom_height: 70
  top_height: 80
  slope: 0.5

hotstart:
  enabled: false

boundary:
  #–– Header ––#
  header: "! ADH BC File - written by will-sat"

  #–– Edge‐string selection ––#
  enabled: true
  interactive: true
  edge_string_names:
    - inlet
    - outlet

  #–– Operation Parameters ––#
  operation:
    SW2: []
    INC: [40]
    TRN: [0]
    BLK: [1]
    PRE: [1]

  #–– Iteration Parameters ––#
  iteration:
    NIT: [10]
    NTL: [0.001]
    ITL: [0.01]
    MIT: [80]

  #–– Constituent Properties ––#
  constituents: []

  #–– Global Material Properties ––#
  global_material:
    MU:  [0.0]
    G:   [9.81]
    RHO: [1000.0]
    MUC: [1.486]

  #–– Material Properties ––#
  materials:
    1:
      - type: EEV
        params: [1, 1.0, 0.0]     # MP EEV 1 1 1.0 0.0
      - type: SRT
        params: [1.0]             # MP SRT 1 1.0
      - type: ML
        params: [0]               # MP ML 1 0
    2:
      - type: EVS
        params: [1, 1.0, 0.0]     # MP EEV 1 1 1.0 0.0
      - type: SRT
        params: [1.0]             # MP SRT 1 1.0
      - type: ML
        params: [0]               # MP ML 1 0

  #–– Time Series for BCs ––#
  time_series:
    - series_type: XY1
      id: 2
      in_units: 2
      out_units: 0
      points:
        - [0.0, 10.0]
        - [5000.0, 10.0]

    - series_type: XY1
      id: 3
      in_units: 2
      out_units: 0
      points:
        - [0.0, 78.0]
        - [5000.0, 78.0]
    - series_type: XY1
      id: 4
      in_units: 2
      out_units: 0
      file: /path/to/data/here.txt
      
    - series_type: XY1
      id: 5
      in_units: 2
      out_units: 0
      file: /path/to/data/here.txt

  #–– Output Series (OS) ––#
  output_control:
    OS:
      - series: 1
        segments:
          - [0.0, 5000.0, 10.0, 0]

  #–– Friction Controls ––#
  friction:
    MNG:
      - region: 1
        params: [0.02]
  friction:
    MNG:
      - region: 2
        params: [0.05]

  #–– Solution Controls ––#
  db: {}
  nb:
    OTW:
      - string: inlet
        series: [2]   # maps to “NB OTW 3 3”
    DIS:
      - string: outlet
        series: [3]   # maps to “NB DIS 2 2”

  #–– Time Controls ––#
  time_controls:
    T0: [0.0, 0]
    TF: [5000.0, 0]
    IDT: [0]




