bbox: [min_lat, min_long, max_lat, max_long]
output_dir: 'output_dir'
loc_tag: 'location_name_here'
project_name: "project_id_here"


shapefile: false
shapefile_path: "shapefile_here.shp"

exclusion:
  enabled: false
dem:
  n_subboxes: 10
  sigma: 2

sentinel:
  num_samples: 10

classification:
  num_samples: 5000
  dilation_iterations: 3
  erosion_iterations: 1

meshing:
  curvi: true
  ni: 49
  nj: 499
  size: 20.0
  smoothing_iterations: 10
  chaikin_alpha:       0.5
  resample_len_frac:   0.10
  boundary_tol: 7.0
  interactive: true

bathymetry:
  shape: parabola
  bottom_height: 1.0
  top_height: 1.75
  slope: 0.5
  orientation: auto

hotstart:
  enabled: false

boundary:
  enabled: false


