bbox: [-91.7635618, 31.1946563, -91.7035031, 31.2287368]
output_dir: 'output/path/here'
loc_tag: 'location_tag_here'
project_name: "earth-engine-project-here"


shapefile: true
shapefile_path: "shapefile/path/here"

exclusion:
  enabled: false
dem:
  n_subboxes: 10
  sigma: 2

sentinel:
  num_samples: 10
  scale: 20
  start_date: '2023-01-01'
  end_date: '2023-06-30'

classification:
  num_samples: 5000
  dilation_iterations: 2
  erosion_iterations: 2

meshing:
  curvi: true
  ni: 49
  nj: 499
  size: 20.0
  smoothing_iterations: 10
  chaikin_alpha:       0.5
  resample_len_frac:   0.10
  boundary_tol: 7.0
  interactive: true

bathymetry:
  shape: parabola
  bottom_height: 70
  top_height: 80
  slope: 0.5

hotstart:
  enabled: false

boundary:
  enabled: false


