bbox: [-91.7635618, 31.1946563, -91.7035031, 31.2287368]
output_dir: 'output_directory_here"
loc_tag: 'location_name_here'
project_name: "earth_engine_project_name_here
dilation_iterations: 10

dem:
  n_subboxes: 10
  sigma: 2

sentinel:
  num_samples: 10

classification:
  num_samples: 5000

meshing:
  curvi: true
  ni: 8
  nj: 150
  size: 20.0
  smoothing_iterations: 10
  chaikin_alpha:       0.5    
  resample_len_frac:   0.10   
  boundary_tol: 5.0
  interactive: true
  
hotstart:
  enabled: false             

boundary:
  enabled: false


