bbox: [-91.7635618, 31.1946563, -91.7035031, 31.2287368]
output_dir: 'C:\data\mlc_test'
loc_tag: 'red_river'
project_name: "water-seg-wdm230"
dilation_iterations: 10

dem:
  n_subboxes: 10
  sigma: 2

sentinel:
  num_samples: 10

classification:
  num_samples: 5000

meshing:
  size: 20.0
  smoothing_iterations: 10
  chaikin_alpha:       0.5    
  resample_len_frac:   0.10   
  boundary_tol: 7.5

  
hotstart:
  enabled: true             
  mode: constant_depth            
  value: 5                  
  use_initial_velocity: false

boundary:
  global_material:
    G: [9.81]
    RHO: [1000]
    MU: [1e-6]
    MUC: [1.0]
  materials:
    1:
      - type: EVS
        params: [0.005,0.005,0.0]
      - type: ML
        params: [4]
      - type: SRT
        params: [1e-4]
  iteration:
    NIT: [6]
    MIT: [100]
    NTL: [1e-5]
  operation:
    SW2: null
    INC: [40]
    BLK: [10]
    TRN: [0]
    PRE: [1]
  boundary_strings:
    MTS:
      - [1, 1]
  time_series:
    - type: XY1
      id: 1
      data: 'C:\data\mlc_test\red_river\ts.txt'
    - type: XY1
      id: 2
      data:
       -  [0.0, 0.0]
       -  [1000.0, 10.0]
  nb:
    OTW: [1]
  friction:
    MNG:
      - region: 1
        params: [0.03]
  time_controls:
    T0: [0]
    TF: [1000]
    IDT: [1]
  output_control:
    OC: [1]

