bbox: [32.5756, 25.165, 32.7176, 25.24597]
output_dir: '/home/will/Desktop/'
loc_tag: 'nile_shp'
project_name: "water-seg-wdm230"


shapefile: true
shapefile_path: "/home/will/mesh_maker/nile.shp"

exclusion:
  enabled: false
dem:
  n_subboxes: 10
  sigma: 2

sentinel:
  num_samples: 10

classification:
  num_samples: 5000
  dilation_iterations: 3
  erosion_iterations: 1
  
meshing:
  curvi: true
  ni: 100
  nj: 500
  size: 20.0
  smoothing_iterations: 10
  chaikin_alpha:       0.5    
  resample_len_frac:   0.10   
  boundary_tol: 7.0
  interactive: true
  
hotstart:
  enabled: false             

boundary:
  enabled: false


