name: will_sat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - earthengine-api=1.5.23
  - geopandas=1.1.1
  - matplotlib=3.10.3
  - numpy=2.3.1
  - pillow=11.3.0
  - pyproj=3.7.1
  - pyyaml=6.0.2
  - rasterio=1.4.3
  - requests=2.32.4
  - scikit-learn=1.7.0
  - scipy=1.16.0
  - setuptools=80.8.0
  - shapely=2.1.1
  - pygridgen=0.3.0
  - scikit-image=0.25.2
  - pip
  - pip:
    - opencv_python_headless==4.12.0.88
    - triangle==20250106
    - trimesh==4.6.13
